### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xie-qianyue**
figure out that the exercises are only verified under koa 1, but not koa 2.

### CODE REVIEW

**Comment by hemanth** [comment]
Any specific issues you noticed?

**Comment by xie-qianyue** [comment]
@hemanth yes, please see [this issue](https://github.com/koajs/kick-off-koa/issues/36). I'm not sure whether it concerns the version, but as @dead-horse says, maybe it's the version problem.

**Comment by hemanth** [comment]
Hmm, rather than updating the readme, it's better we migrate to `2.0` it be nice if you could modify the text to something like:

> Note that the exercises of kick-off are only verified under koa 1, but <strong>NOT</strong> koa 2. Meanwhile we are migrating to kao 2 and you can also take part in it.

**Comment by tejasmanohar** [comment]
:+1: for what @hemanth said since we do want to have Koa 2 stuff eventually too :)

**Comment by xie-qianyue** [comment]
@hemanth I have modified the READ ME as you proposed. I will test the exercises under koa 2. If I find something wrong, I will create the issue.

**Comment by hemanth** [comment]
@xie-qianyue Cool, thanks. 

Please have a single issue with checklists.

**Pull request merged**
