### PR TITLE
L10n fr

### PR DESCRIPTION
**Pull request by tdd**
Hey guys!

First, thanks for Koa and for this workshopper. Really cool stuff.

As part of the nodeschool/organizers#64 effort, we're currently upgrading all `workshopper`-based workshops to the latest infrastructure then adding translations, so this is French.

Our translations always get proofread by extra translators before submission: this was proofread and tweaked in deliciousinsights/kick-off-koa#1.

It would be great if this could get merged in and published to npm before April 11, which is the next NodeSchool Paris event! :wink: 

If you have any question, don't hesitate to ask!

Best,

### CODE REVIEW

**Comment by dead-horse** [comment]
that's fantastic!
thanks for your great work!

**Comment by dead-horse** [comment]
2.0.0 published

**Comment by tdd** [comment]
Thanks!

**Comment by fengmk2** [comment]
Great!

**Comment by hemanth** [comment]
:+1:

**Pull request merged**
